"use client";

import { useRef, useState, type ReactNode } from "react";
import { useAuth } from "@clerk/nextjs";
import { AlertTriangle, Paperclip, Send } from "lucide-react";

import type { SupportEntryType, Upload } from "@/lib/api-types";
import { createTicketEntry } from "@/lib/support-api";
import { uploadThreadAttachment, downloadUpload } from "@/lib/global-api";
import { MessageEditor } from "@/components/editor/message-editor";

/**
 * Entry type options visible to DEFT agents.
 * system_event is intentionally excluded — it is auto-generated by the system
 * (e.g. when the ticket status changes) and must never be a manual entry.
 */
const DEFT_ENTRY_TYPES: { value: SupportEntryType; label: string; description: string }[] = [
  {
    value: "agent_reply",
    label: "Reply (publish now)",
    description: "Immediately visible to the customer.",
  },
  {
    value: "draft",
    label: "Draft",
    description: "Saved as a draft — only you can see it until published.",
  },
  {
    value: "context",
    label: "Internal note",
    description: "DEFT-only. Never visible to the customer.",
  },
  {
    value: "customer",
    label: "Customer message",
    description: "Add a message on the customer’s behalf.",
  },
];

/**
 * Entry type options visible to customers (non-DEFT members).
 * Customers can compose a normal message or save a draft for later.
 */
const CUSTOMER_ENTRY_TYPES: { value: SupportEntryType; label: string; description: string }[] = [
  { value: "customer", label: "Message", description: "Send a message to the support team." },
  {
    value: "draft",
    label: "Draft",
    description: "Save a draft — only you and DEFT support can see it until you send it.",
  },
];

/** Props for TicketEntryComposer. */
export interface TicketEntryComposerProps {
  /** Slug of the parent ticket. */
  ticketSlug: string;
  /** Whether the current user is a DEFT member (shows advanced type options). */
  isDeftMember: boolean;
  /** Called after a new entry is successfully created. */
  onCreated?: () => void;
}

/**
 * TicketEntryComposer renders the rich-text input area for adding new entries
 * to a support ticket.
 * — DEFT members see 4 entry type buttons (agent_reply, draft, context, customer).
 * — Customers see 2 type buttons (message, draft).
 * — system_event is excluded — created automatically when status changes.
 * — The “Hide from customer” checkbox is shown only to DEFT members.
 * — File attachments can be uploaded per entry session.
 */
export function TicketEntryComposer({
  ticketSlug,
  isDeftMember,
  onCreated,
}: TicketEntryComposerProps): ReactNode {
  const { getToken } = useAuth();
  const entryTypes = isDeftMember ? DEFT_ENTRY_TYPES : CUSTOMER_ENTRY_TYPES;

  const [entryType, setEntryType] = useState<SupportEntryType>(
    isDeftMember ? "agent_reply" : "customer",
  );
  const [isDeftOnly, setIsDeftOnly] = useState(false);
  const [body, setBody] = useState("");
  const [submitting, setSubmitting] = useState(false);
  const [error, setError] = useState("");

  // File attachment state.
  const [attachments, setAttachments] = useState<Upload[]>([]);
  const [uploading, setUploading] = useState(false);
  const [attachError, setAttachError] = useState("");
  const fileInputRef = useRef<HTMLInputElement>(null);

  const handleAttach = async (e: React.ChangeEvent<HTMLInputElement>): Promise<void> => {
    const file = e.target.files?.[0];
    if (!file) return;
    if (fileInputRef.current) fileInputRef.current.value = "";
    setAttachError("");
    setUploading(true);
    try {
      const token = await getToken();
      if (!token) return;
      const uploaded = await uploadThreadAttachment(token, ticketSlug, file);
      setAttachments((prev) => [...prev, uploaded]);
    } catch (err) {
      setAttachError(err instanceof Error ? err.message : "Upload failed");
    } finally {
      setUploading(false);
    }
  };

  const handleDownload = async (uploadId: string, filename: string): Promise<void> => {
    const token = await getToken();
    if (!token) return;
    await downloadUpload(token, uploadId, filename);
  };

  const handleSubmit = async (): Promise<void> => {
    if (!body.trim()) return;
    setError("");
    setSubmitting(true);
    try {
      const token = await getToken();
      if (!token) return;
      await createTicketEntry(token, ticketSlug, {
        type: entryType,
        body,
        is_deft_only: isDeftOnly || entryType === "context",
      });
      setBody("");
      setAttachments([]);
      onCreated?.();
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to submit");
    } finally {
      setSubmitting(false);
    }
  };

  return (
    <div data-testid="ticket-entry-composer" className="flex flex-col gap-3 p-4">
      {/* Entry type selector */}
      <div>
        <label className="text-xs font-medium text-foreground">Type</label>
        <div className="mt-1 flex flex-wrap gap-2">
          {entryTypes.map(({ value, label }) => (
            <button
              key={value}
              data-testid={`entry-type-btn-${value}`}
              onClick={() => setEntryType(value)}
              className={`rounded-md px-3 py-1 text-xs font-medium transition-colors ${
                entryType === value
                  ? "bg-primary text-primary-foreground"
                  : "border border-border bg-background text-foreground hover:bg-accent"
              }`}
            >
              {label}
            </button>
          ))}
        </div>
        <p className="mt-1 text-xs text-muted-foreground">
          {entryTypes.find((t) => t.value === entryType)?.description ?? ""}
        </p>
      </div>

      {/* DEFT-only toggle — only for customer-visible DEFT replies */}
      {isDeftMember && entryType === "agent_reply" && (
        <label className="flex items-center gap-2 text-xs text-muted-foreground">
          <input
            data-testid="deft-only-checkbox"
            type="checkbox"
            checked={isDeftOnly}
            onChange={(e) => setIsDeftOnly(e.target.checked)}
            className="h-3 w-3"
          />
          Hide from customer (DEFT only)
        </label>
      )}

      {/* Rich text editor — half-page height */}
      <MessageEditor
        initialContent={body}
        onSubmit={() => void handleSubmit()}
        onChange={setBody}
        placeholder="Write a message…"
        disabled={submitting}
        showSubmit={false}
        editorMinHeight="50vh"
        imageOptions={attachments
          .filter((a) => a.content_type.startsWith("image/"))
          .map((a) => ({ label: a.filename, url: a.storage_path }))}
      />

      {/* File attachments */}
      <div>
        <div className="flex items-center justify-between">
          <span className="text-xs font-medium text-foreground">Attachments</span>
          <label
            htmlFor="composer-file-input"
            data-testid="composer-attach-btn"
            className="inline-flex cursor-pointer items-center gap-1 rounded-md border border-border px-2 py-1 text-xs font-medium text-foreground hover:bg-accent"
          >
            <Paperclip className="h-3 w-3" />
            {uploading ? "Uploading…" : "Attach file"}
          </label>
          <input
            id="composer-file-input"
            ref={fileInputRef}
            type="file"
            className="hidden"
            onChange={(e) => void handleAttach(e)}
            disabled={uploading}
          />
        </div>
        {attachError && (
          <p data-testid="attach-error" className="mt-1 text-xs text-red-600">
            {attachError}
          </p>
        )}
        {attachments.length > 0 && (
          <ul data-testid="attachments-list" className="mt-2 space-y-1">
            {attachments.map((a) => (
              <li key={a.id} className="flex items-center gap-1 text-xs">
                <Paperclip className="h-3 w-3 shrink-0 text-muted-foreground" />
                <button
                  onClick={() => void handleDownload(a.id, a.filename)}
                  className="truncate text-foreground underline hover:no-underline"
                >
                  {a.filename}
                </button>
                <span className="shrink-0 text-muted-foreground">
                  ({(a.size / 1024).toFixed(1)} KB)
                </span>
              </li>
            ))}
          </ul>
        )}
      </div>

      {/* Error banner */}
      {error && (
        <div
          data-testid="composer-error"
          className="flex items-center gap-2 rounded-md bg-red-50 px-3 py-2 text-sm text-red-700"
        >
          <AlertTriangle className="h-4 w-4 shrink-0" />
          {error}
        </div>
      )}

      {/* Submit */}
      <div className="flex justify-end">
        <button
          data-testid="composer-submit-btn"
          onClick={() => void handleSubmit()}
          disabled={submitting || !body.trim()}
          className="inline-flex items-center gap-1.5 rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground hover:bg-primary/90 disabled:opacity-50"
        >
          <Send className="h-4 w-4" />
          {submitting ? "Sending…" : entryType === "draft" ? "Save draft" : "Send"}
        </button>
      </div>
    </div>
  );
}
